name: CI Check Code with Detekt

on: pull_request

jobs:
  build:
    name: CI Check Code with Detekt
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: Run Action Detekt
        uses: alaegin/Detekt-Action@v1.21.0-RC2
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: config/detekt/detekt.yml
          fail_on_error: true
          detekt_parallel: true
          detekt_all_rules: true
          reviewdog_reporter: github-pr-review
          reviewdog_level: error,info,warning

